config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  


  # Defines the root path route ("/")
  root "chatroom#index"
  get "login", to: "sessions#new"
  post 'login', to: "sessions#create"
  get "signup", to: "users#new"
  delete "logout", to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
    has_many :messages
    validates :bio, presence: true, 
                    length: { minimum: 4, maximum: 300 }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
      !!current_user
    end

    def require_user
      return if logged_in?

      flash[:alert]="You must be logged in to perform that action"
      redirect_to login_path
    end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @messages = Message.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to message_url(@message), notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy!

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:body, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new
    
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in successfully'
      redirect_to user
    else 
      flash.now[:alert] = "There was something wrong with your login details."
      render :new, status: 401
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:alert] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_user, only: %i[edit update]
  before_action :require_same_user, only: %i[edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :email, :first_name, :last_name)
    end

    def require_same_user
      return unless current_user != @user && !current_user.admin?

      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
    <i class="circular orange coffee icon"></i>
    Say Something
</h4>

<div class="ui two column grid">
    <div class="twelve wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content">
                <div class="ui feed">
                    <%= render @messages %>
                </div>
            </div>
                <div class="extra content">
                    <form class="ui reply form">
                        <div class="field">
                            <div class="ui fluid icon input">
                                <input type="text" placeholder="Enter a message...">
                                <i class="bordered inverted orange edit icon"></i>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
    </div>

    <div class="four wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content">
                <div class="ui inverted vertical menu">
                    <a class="item">
                        Home
                    </a>
                    <a class="item">
                        Messages
                    </a>
                    <a class="item">
                        Friends
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="ui inverted menu">
    <div class="ui container">
        <a class="item" href="/">
            Home
        </a>
        <a class="item">
            Messages
        </a>
        <div class="right menu">
            <div class="ui dropdown item">
            Account <i class="dropdown icon"></i>
                <div class="menu">
                    <% if !logged_in? %>
                        <a class="item" href="/signup">Sign up</a>
                        <a class="item" href="/login">Log in</a>
                    <% else %>
                        <%= link_to "Profile", user_path(current_user), class: "item" %>
                    <% end %>
                </div>
            </div>
            <div class="item">
                <% if logged_in? %>
                    <%= button_to "Log out", logout_path, class: "ui orange button", method: :delete %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_notifications.html.erb
<% flash.each do |name, msg| %>
    <div class="ui <%= name == "notice" ? "success" : "negative" %> message">
        <i class="close icon"></i>
        <div class="header">
            <%= msg %>
        </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/notifications' %>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
      <div class="summary">
          <em><%= message.user.username %></em>: <%= message.body %>
      </div>
  </div>
</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
      <%= link_to "Show this message", message %>
    </p>
  <% end %>
</div>

<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div style="color: red">
    <h2><%= pluralize(obj.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% obj.errors.each do |error| %>
        <li><%= error.full_message %></li>
    <% end %>
    </ul>
</div>
<% end %>

app/views/users/_form.html.erb
<div class="ui segment signup four column center aligned grid">
  <%= render 'shared/errors', obj: @user %>
    <%= form_with(model: @user, class: "ui form") do |form| %>
          <div class="field">
            <%= form.label :username, style: "display: flex" %>
            <%= form.text_field :username, placeholder: "Username" %>
          </div>

          <div class="field">
            <%= form.label :password, style: "display: flex" %>
            <%= form.password_field :password, placeholder: "Password" %>
          </div>

          <div class="field">
            <%= form.label :email, style: "display: flex" %>
            <%= form.email_field :email, placeholder: "Email" %>
          </div>

        <div class="field">
          <%= form.label :first_name, style: "display: flex" %>
          <%= form.text_field :first_name, placeholder: "First name" %>
        </div>

        <div class="field">
          <%= form.label :last_name, style: "display: flex"%>
          <%= form.text_field :last_name,  placeholder: "Last name"  %>
        </div>

      <div class="two column row">
        <%= form.label :bio, style: "display: flex" %>
        <%= form.text_area :bio, placeholder: "Enter your bio" %>
      </div>
      
      <br/>
      <div>
        <%= form.submit "Sign Up", class: "ui submit button" %>
      </div>
    <% end %>
</div>

app/views/users/_user.html.erb
<div class="ui two column grid">
  <div class="sixteen wide column">
      <div class="ui fluid raised card chatbox">
        <div class="content">
          <div class="ui header center aligned">
              Username: <em><%= @user.username %></em>
          </div>
          <div class="ui header center aligned">
              Email: <em><%= @user.email %></em>
          </div>
          <div class="ui header center aligned">
              Full name: <em><%= @user.first_name.capitalize %></em> <em><%= @user.last_name.capitalize %></em>
          </div>
          <br/>
          <div class="ui horizontal divider">
            Actions
          </div>
          <% if current_user.admin? || current_user == @user %>
            <div class="ui center aligned">
              <%= link_to "Edit this account", edit_user_path(@user), class: "ui inverted blue button" %>
              <%= button_to "Delete this account", @user, method: :delete, class: "ui inverted red button" %>
            </div>
          <% end %>
      </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h4 class="ui center aligned medium icon header">
    <i class="circular orange user icon"></i> Users
</h4>
<div id="users" class="ui cards centered align">
  <% @users.each do |user| %>
    <div class="ui card">
      <div class="content">
        <%= link_to user.username, user_path(user), class: "header"%> 
        <div class="meta">
          <span class="date">Joined <%= time_ago_in_words(user.created_at) %> ago</span>
        </div>
        <div class="description">
          <%= user.bio %>
        </div>
      </div>
</div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1 class="ui centered grid">Sign Up</h1>

<div class="ui two column centered grid">
<%= render "form", user: @user %>
</div>

<div class="ui centered grid">
  <%= link_to "[ Back to users ]", users_path  %>
</div>

app/views/users/show.html.erb
<h4 class="ui center aligned medium icon header">
    <i class="circular orange user icon"></i> <%= @user.username %>'s Profile
</h4>

<%= render @user %>

<div class="ui center aligned medium icon header">
  <%= link_to "[ Back to users ]", users_path %>
</div>